repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
        - id: ruff-format
          name: ruff-format
          entry: pixi run --environment dev format
          language: system
          types: [python]
